### ISSUE TITLE
alpine的tun默认是关闭

### ISSUE THREAD

**Issue by le0liu** [byxiaopeng/clash#2]
每次重新更新镜像都要手动开启一遍tun,能否在制作镜像时开启一下,非常感谢.

**Comment by byxiaopeng** [comment]
由于我使用modprobe tun命令返回错误代码

**Comment by le0liu** [comment]
mkdir /lib/modules
modprobe tun
mkdir /lib/modules/4.4.167
modprobe tun

**Comment by byxiaopeng** [comment]
已添加自定义shell脚本   自己查看最新说明文档
