### ISSUE TITLE
能不能集成Web？

### ISSUE THREAD

**Issue by efsg** [byxiaopeng/clash#3]
我看了下虽然有下载yacd但是没有使用，可以集成nginx吗

**Comment by byxiaopeng** [comment]
external-ui: dashboard

**Comment by efsg** [comment]
> config.yaml添加
> external-controller: 0.0.0.0:9090
> secret: ""
> external-ui: dashboard
> 就可以开启web面板

感谢大佬解答！我刚用Clash还没上手，大佬的镜像部署在NAS当代理网关很棒

**Comment by efsg** [comment]
> config.yaml添加
> external-controller: 0.0.0.0:9090
> secret: ""
> external-ui: dashboard
> 就可以开启web面板

大佬我又遇到了回流的问题，连接NAS当网关后内网不能访问路由器DDNS+端口转发NAS的服务，网上其他人反而是外网访问内网不能回流

**Comment by efsg** [comment]
解决了，在iptables的TPROXY前添加一条`iptables -t mangle -A clash -m addrtype --dst-type LOCAL -j RETURN`
https://github.com/Dreamacro/clash/issues/841#issuecomment-673926508
